language: objective-c
osx_image: xcode11.3
script: xcodebuild clean build -project Subscribe.xcodeproj -scheme Subscribe -sdk iphonesimulator -destination"platform=iOS Simulator,OS=12.1,name=iPhone 6" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
